# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GMWColourLayers
                                 A QGIS plugin
 A plugin which colours layers 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-09
        copyright            : (C) 2026 by Pete Bunting
        email                : petebunting@mac.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GMWColourLayers class from file GMWColourLayers.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gmw_colour_layers import GMWColourLayers
    return GMWColourLayers(iface)
